command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "kafka-app-warehouse-id"
  - name: KAFKA_BOOTSTRAP_SERVERS
    valueFrom: "kafka-app-bootstrap-servers"
  - name: KAFKA_INPUT_TOPIC
    valueFrom: "kafka-app-input-topic"
  - name: KAFKA_OUTPUT_TOPIC
    valueFrom: "kafka-app-output-topic"
  - name: KAFKA_GROUP_ID
    valueFrom: "kafka-app-group-id"
  - name: DATABRICKS_MODEL_ENDPOINT
    valueFrom: "kafka-app-model-endpoint"
  - name: KAFKA_SECURITY_PROTOCOL
    valueFrom: "kafka-app-security-protocol"
  - name: KAFKA_SASL_MECHANISM
    valueFrom: "kafka-app-sasl-mechanism"
  - name: KAFKA_SASL_USERNAME
    valueFrom: "kafka-app-username"
  - name: KAFKA_SASL_PASSWORD
    valueFrom: "kafka-app-password"

